// <auto-generated />
using System;
using CarMember_server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarMember_server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250404143812_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarMember_server.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comment");

                    b.Property<Guid>("IdAuthorUser")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_author_user");

                    b.Property<Guid>("IdReviewedUser")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_reviewed_user");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.HasIndex("IdAuthorUser");

                    b.HasIndex("IdReviewedUser");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CarMember_server.Models.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnimalReference")
                        .HasColumnType("int")
                        .HasColumnName("animal_preference ");

                    b.Property<string>("ArrivalLocationAdress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("arrival_location_adress");

                    b.Property<string>("ArrivalLocationCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("arrival_location_city");

                    b.Property<string>("CostCheeseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cost_cheese_type");

                    b.Property<int>("CostHeight")
                        .HasColumnType("int")
                        .HasColumnName("cost_height");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("departure_date");

                    b.Property<string>("DepartureLocationAdress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("departure_location_adress");

                    b.Property<string>("DepartureLocationCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departure_location_city");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("MusicalReference")
                        .HasColumnType("int")
                        .HasColumnName("musical_preference ");

                    b.Property<int>("SmokingReference")
                        .HasColumnType("int")
                        .HasColumnName("smoking_preference  ");

                    b.Property<int>("TalkingReference")
                        .HasColumnType("int")
                        .HasColumnName("talking_preference  ");

                    b.HasKey("Id");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("CarMember_server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("creation_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstname");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gender");

                    b.Property<Guid?>("IdVehiculeModel")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_vehicule_model");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lasttname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password_salt");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("profile_picture");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("IdVehiculeModel");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CarMember_server.Models.VehiculeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int")
                        .HasColumnName("number_of_seats");

                    b.HasKey("Id");

                    b.ToTable("VehiculeModels");
                });

            modelBuilder.Entity("RideUser", b =>
                {
                    b.Property<Guid>("RidesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RidesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RideUser");
                });

            modelBuilder.Entity("CarMember_server.Models.Review", b =>
                {
                    b.HasOne("CarMember_server.Models.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("IdAuthorUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarMember_server.Models.User", "ReviewedUser")
                        .WithMany("Reviews")
                        .HasForeignKey("IdReviewedUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("ReviewedUser");
                });

            modelBuilder.Entity("CarMember_server.Models.User", b =>
                {
                    b.HasOne("CarMember_server.Models.VehiculeModel", "VehiculeModel")
                        .WithMany("Users")
                        .HasForeignKey("IdVehiculeModel");

                    b.Navigation("VehiculeModel");
                });

            modelBuilder.Entity("RideUser", b =>
                {
                    b.HasOne("CarMember_server.Models.Ride", null)
                        .WithMany()
                        .HasForeignKey("RidesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarMember_server.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarMember_server.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CarMember_server.Models.VehiculeModel", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
