// <auto-generated />
using System;
using CarMember_server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarMember_server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarMember_server.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("comment");

                    b.Property<Guid?>("ReviewedUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reviewed_user_id");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ReviewedUserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("858eb3be-9850-49a7-9925-02c2c8f5229a"),
                            AuthorUserId = new Guid("315dd23f-0155-4196-90eb-f00e2db27014"),
                            Comment = "Super trajet avec Igor, peu bavard mais très accueuillant ! Edmond.",
                            ReviewedUserId = new Guid("6d4b945a-8e33-4008-af4c-37fc28b893a4"),
                            Score = 5
                        },
                        new
                        {
                            Id = new Guid("ff666e12-1475-41a8-ac4f-188eaf83cb6c"),
                            AuthorUserId = new Guid("6d4b945a-8e33-4008-af4c-37fc28b893a4"),
                            Comment = "Pas sympathique et trop bavard, Mozart est trop vieux jeu ! Igor",
                            ReviewedUserId = new Guid("49f88bba-7235-44b3-9b03-2396a5d086a8"),
                            Score = 3
                        });
                });

            modelBuilder.Entity("CarMember_server.Models.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnimalReference")
                        .HasColumnType("int")
                        .HasColumnName("animal_preference");

                    b.Property<string>("ArrivalLocationAdress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("arrival_location_adress");

                    b.Property<string>("ArrivalLocationCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("arrival_location_city");

                    b.Property<int>("CostCheeseType")
                        .HasColumnType("int")
                        .HasColumnName("cost_cheese_type");

                    b.Property<int>("CostHeight")
                        .HasColumnType("int")
                        .HasColumnName("cost_height");

                    b.Property<DateTime?>("DepartureDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("departure_date");

                    b.Property<string>("DepartureLocationAdress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("departure_location_adress");

                    b.Property<string>("DepartureLocationCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departure_location_city");

                    b.Property<Guid>("DriverUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("driver_user_id");

                    b.Property<int>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("duration");

                    b.Property<int>("MusicalReference")
                        .HasColumnType("int")
                        .HasColumnName("musical_preference");

                    b.Property<int>("SmokingReference")
                        .HasColumnType("int")
                        .HasColumnName("smoking_preference");

                    b.Property<int>("TalkingReference")
                        .HasColumnType("int")
                        .HasColumnName("talking_preference");

                    b.HasKey("Id");

                    b.HasIndex("DriverUserId");

                    b.ToTable("Rides");

                    b.HasData(
                        new
                        {
                            Id = new Guid("95df620f-ae38-4e5a-8894-41332c14c4c5"),
                            AnimalReference = 1,
                            ArrivalLocationAdress = "6 Avenue des Champs Elysées",
                            ArrivalLocationCity = "Paris",
                            CostCheeseType = 6,
                            CostHeight = 1000,
                            DepartureDate = new DateTime(2025, 4, 20, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocationAdress = "3 rue Faidherbe",
                            DepartureLocationCity = "Lille",
                            DriverUserId = new Guid("6d4b945a-8e33-4008-af4c-37fc28b893a4"),
                            Duration = 180,
                            MusicalReference = 3,
                            SmokingReference = 1,
                            TalkingReference = 3
                        },
                        new
                        {
                            Id = new Guid("4253b6c2-a9ae-4ea9-97b4-2e88d5348a56"),
                            AnimalReference = 0,
                            ArrivalLocationAdress = "4 parvis Victor Hugo, Dunkerque",
                            ArrivalLocationCity = "Dunkerque",
                            CostCheeseType = 2,
                            CostHeight = 600,
                            DepartureDate = new DateTime(2025, 4, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureLocationAdress = "3 rue Faidherbe, 59000 Lille",
                            DepartureLocationCity = "Lille",
                            DriverUserId = new Guid("315dd23f-0155-4196-90eb-f00e2db27014"),
                            Duration = 60,
                            MusicalReference = 2,
                            SmokingReference = 0,
                            TalkingReference = 1
                        });
                });

            modelBuilder.Entity("CarMember_server.Models.RideUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ride_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.HasIndex("UserId");

                    b.ToTable("RideUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("729ec28d-8649-4ff4-a3da-74f776e05128"),
                            RideId = new Guid("95df620f-ae38-4e5a-8894-41332c14c4c5"),
                            UserId = new Guid("315dd23f-0155-4196-90eb-f00e2db27014")
                        });
                });

            modelBuilder.Entity("CarMember_server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("creation_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firstname");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password_salt");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("profile_picture");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<Guid?>("VehiculeModelId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicule_model_id");

                    b.HasKey("Id");

                    b.HasIndex("VehiculeModelId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49f88bba-7235-44b3-9b03-2396a5d086a8"),
                            CreationDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mozart.ella@mail.com",
                            FirstName = "Mozart",
                            Gender = "F",
                            LastName = "Ella",
                            Password = "TODO",
                            PasswordSalt = "TODO",
                            PhoneNumber = "+3368856115",
                            Role = "admin",
                            VehiculeModelId = new Guid("2eefbb1b-b7b0-4d0d-834a-90ca46f636c2")
                        },
                        new
                        {
                            Id = new Guid("6d4b945a-8e33-4008-af4c-37fc28b893a4"),
                            CreationDate = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "igor.gonzolla@mail.com",
                            FirstName = "Igor",
                            Gender = "H",
                            LastName = "Gonzola",
                            Password = "TODO",
                            PasswordSalt = "TODO",
                            PhoneNumber = "+3361142415",
                            Role = "user",
                            VehiculeModelId = new Guid("66a15c74-4ee7-477d-85b2-a3f084c58142")
                        },
                        new
                        {
                            Id = new Guid("315dd23f-0155-4196-90eb-f00e2db27014"),
                            CreationDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "edmond.dor@mail.com",
                            FirstName = "Edmond",
                            Gender = "H",
                            LastName = "d'Or",
                            Password = "TODO",
                            PasswordSalt = "TODO",
                            PhoneNumber = "+336888815",
                            Role = "user"
                        });
                });

            modelBuilder.Entity("CarMember_server.Models.VehiculeModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int")
                        .HasColumnName("number_of_seats");

                    b.HasKey("Id");

                    b.ToTable("VehiculeModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2eefbb1b-b7b0-4d0d-834a-90ca46f636c2"),
                            Category = 10,
                            Name = "Chèvre-O-lait",
                            NumberOfSeats = 5
                        },
                        new
                        {
                            Id = new Guid("66a15c74-4ee7-477d-85b2-a3f084c58142"),
                            Category = 2,
                            Name = "Munster-Truck",
                            NumberOfSeats = 4
                        });
                });

            modelBuilder.Entity("CarMember_server.Models.Review", b =>
                {
                    b.HasOne("CarMember_server.Models.User", "AuthorUser")
                        .WithMany("AuthorReviews")
                        .HasForeignKey("AuthorUserId");

                    b.HasOne("CarMember_server.Models.User", "ReviewedUser")
                        .WithMany("ReviewedReviews")
                        .HasForeignKey("ReviewedUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("AuthorUser");

                    b.Navigation("ReviewedUser");
                });

            modelBuilder.Entity("CarMember_server.Models.Ride", b =>
                {
                    b.HasOne("CarMember_server.Models.User", "DriverUser")
                        .WithMany("ConductorRides")
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverUser");
                });

            modelBuilder.Entity("CarMember_server.Models.RideUser", b =>
                {
                    b.HasOne("CarMember_server.Models.Ride", "Ride")
                        .WithMany("RideUsers")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarMember_server.Models.User", "User")
                        .WithMany("RideUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarMember_server.Models.User", b =>
                {
                    b.HasOne("CarMember_server.Models.VehiculeModel", "VehiculeModel")
                        .WithMany("Users")
                        .HasForeignKey("VehiculeModelId");

                    b.Navigation("VehiculeModel");
                });

            modelBuilder.Entity("CarMember_server.Models.Ride", b =>
                {
                    b.Navigation("RideUsers");
                });

            modelBuilder.Entity("CarMember_server.Models.User", b =>
                {
                    b.Navigation("AuthorReviews");

                    b.Navigation("ConductorRides");

                    b.Navigation("ReviewedReviews");

                    b.Navigation("RideUsers");
                });

            modelBuilder.Entity("CarMember_server.Models.VehiculeModel", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
